### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by csmith** [jonesnxt/kilordle#1]
Not sure if you intended this to be played seriously or if it was just a commentary on the deluge of wordle spin-offs, but it was actually pretty fun! (I took 115 guesses to solve all the boards)

The only problem is on a PC it doesn't seem to accept keyboard input, so those 115 guesses took ~700 mouse clicks which was not the best experience ever! Any chance it can listen to key events and enter the appropriate letters?

**Comment by akeyes** [comment]
Agreed, this is a huge annoyance.

**Comment by CyberFlameGO** [comment]
Yeah, it'd be dope if you got this implemented!

**Comment by jonesnxt** [comment]
Added. Thank you for the recommendation! :+1:
