### ISSUE TITLE
Math Issues

### ISSUE THREAD

**Issue by Rhinozz** [jonesnxt/kilordle#6]
Steps to reproduce:
1. Play a game
2. Scroll to bottom of screen (I'm not sure if this causes the bug but it's what I did most of the game)
3. Enter words until the words remaining starts going down abnormally

As a result, this is possible:
![image](https://user-images.githubusercontent.com/68926744/155221114-d0d90bd8-506d-4ff4-8b35-cb6958b82a48.png)

**Comment by ncovercash** [comment]
This is intentional.  As long as all letters in a word were green at one point, it is marked correct.

Therefore, something like `PRICE` and `GLINT` would complete a word `PRINT`

**Comment by jonesnxt** [comment]
+1 @ncovercash
