### ISSUE TITLE
Pressing the CTRL key causes white screen

### ISSUE THREAD

**Issue by ZagOnEm** [jonesnxt/kilordle#7]
Happens with both CTRL keys and happens every time.

**Comment by jazzpi** [comment]
This also happens when pressing capslock, and pressing shift inputs "shift". I think adding a check if `key.length === 1` to https://github.com/jonesnxt/kilordle/blob/main/src/App.tsx#L35 should help.

**Comment by jonesnxt** [comment]
good catch! Just merged in a fix :+1:
